<?php if (!empty($flash['success'])): ?>
    <div class="alert alert-success"><?= htmlspecialchars($flash['success'][0]) ?></div>
<?php endif; ?>
<?php if (!empty($flash['info'])): ?>
    <div class="alert alert-success"><?= htmlspecialchars($flash['info'][0]) ?></div>
<?php endif; ?>
<?php if (!empty($flash['error'])): ?>
    <div class="alert alert-danger"><?= htmlspecialchars($flash['error'][0]) ?></div>
<?php endif; ?>
<main class="flex-grow-1">
    <div class="container-lg mt-3">
        
        <h1>Сайт: <?= htmlspecialchars($url['name']) ?></h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                    <tr>
                        <td>ID</td>
                        <td><?= htmlspecialchars($url['id']) ?></td>
                    </tr>
                    <tr>
                        <td>Имя</td>
                        <td><?= htmlspecialchars($url['name']) ?></td>
                    </tr>
                    <tr>
                        <td>Дата создания</td>
                        <td><?= htmlspecialchars($url['created_at']) ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <h2 class="mt-5 mb-3">Проверки</h2>
        <form method="post" action="/urls/<?= htmlspecialchars($url['id']) ?>/checks" class="mb-3">
            <input type="submit" class="btn btn-primary" value="Запустить проверку">
        </form>
        <table class="table table-bordered table-hover" data-test="checks">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Код ответа</th>
                    <th>h1</th>
                    <th>title</th>
                    <th>description</th>
                    <th>Дата создания</th>
                </tr>
            </thead>
            <tbody> 
                <?php foreach ($checks as $check): ?>
                    <tr>
                        <td><?= htmlspecialchars($check['id']) ?></td>
                        <td><?= htmlspecialchars($check['status_code']) ?></td>
                        <td><?= htmlspecialchars($check['h1'] ?? '') ?></td>
                        <td><?= htmlspecialchars($check['title'] ?? '') ?></td>
                        <td><?= htmlspecialchars($check['description'] ?? '') ?></td>
                        <td><?= htmlspecialchars($check['created_at']) ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</main>