name: Tests
on: push
jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
        - uses: actions/checkout@v3
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.3'
        - run: make install
        - run: make lint 